import { Inter } from 'next/font/google'
import './global.css'

import Menu from './Menu.jsx'
console.log(Menu)

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dorset Inframe Cabinetry',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} font-light`}>
        <Menu />
        {children}
      </body>
    </html>
  )
}
