import { Inter } from 'next/font/google'
import './globals.css'

import Nav from './Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dorset Inframe Cabinetry',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} font-light`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
