import '../global.css'

import NavDesktop from '@/app/(general)/NavDesktop'
import NavMobile from '@/app/(general)/NavMobile'

export const metadata = {
  title: 'Dorset Inframe Cabinetry',
  description: 'Generated by create next app'
}

export default function Layout({ children }) {
  return (
    <>
      <NavMobile />
      <NavDesktop />
      {children}
    </>
  )
}
